# Generated by Django 5.1.6 on 2025-02-12 17:21

import django.db.models.deletion
import django_countries.fields
import uuid
import xero_integration.xero.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('xero_contact_id', models.CharField(blank=True, default='', help_text='Xero Contact ID', max_length=255, verbose_name='Xero Contact ID')),
                ('name', models.CharField(help_text='Name of organization', max_length=255, unique=True, verbose_name='Name')),
                ('email', models.EmailField(blank=True, default='', help_text='Email address of the organization', max_length=254, verbose_name='Email')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('do_not_call', models.BooleanField(default=False)),
                ('linkedin_url', models.URLField(blank=True, null=True, verbose_name='Linked in URL')),
                ('facebook_url', models.URLField(blank=True, null=True, verbose_name='Facebook URL')),
                ('twitter_username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Twitter username')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('is_supplier', models.BooleanField(default=False, verbose_name='supplier')),
                ('is_customer', models.BooleanField(default=False, verbose_name='customer')),
            ],
        ),
        migrations.CreateModel(
            name='ContactAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('POBOX', 'P.O. Box'), ('POSTAL', 'Postal'), ('RESIDENTIAL', 'Residential'), ('STREET', 'Street'), ('DELIVERY', 'Delivery'), ('DIGITAL ADDRESS', 'Digital Address')], default='POBOX', max_length=20, verbose_name='Address Type')),
                ('address_line1', models.CharField(blank=True, default='', max_length=256, verbose_name='Address Line 1')),
                ('address_line2', models.CharField(blank=True, default='', max_length=256, verbose_name='Address Line 2')),
                ('address_line3', models.CharField(blank=True, default='', max_length=256, verbose_name='Address Line 3')),
                ('address_line4', models.CharField(blank=True, default='', max_length=256, verbose_name='Address Line 4')),
                ('city', models.CharField(blank=True, default='', max_length=256, verbose_name='City')),
                ('region', models.CharField(blank=True, default='', help_text='Region', max_length=128, verbose_name='Region')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=256, null=True, verbose_name='country')),
                ('postal_code', models.CharField(blank=True, default='', help_text='Postal code', max_length=20, verbose_name='Postal Code')),
                ('digital_address', models.CharField(blank=True, default='', help_text='Digital Address', max_length=20, verbose_name='Digital Address')),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_addresses', to='xero.contact', verbose_name='Contact/Company/Organisation')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Address',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, default='', max_length=254, verbose_name='Job title')),
                ('first_name', models.CharField(max_length=254, verbose_name='First name')),
                ('last_name', models.CharField(max_length=254, verbose_name='Last name')),
                ('email', models.EmailField(blank=True, default='', max_length=254, null=True, verbose_name='Email')),
                ('phone', xero_integration.xero.utils.PossiblePhoneNumberField(max_length=128, null=True, region=None, verbose_name='Phone number')),
                ('primary_contact', models.BooleanField(default=False, verbose_name='Primary contact')),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_contact_people', to='xero.contact', verbose_name='Contact/Company/Organisation')),
            ],
            options={
                'verbose_name': 'Contact Person',
                'verbose_name_plural': 'Contact Persons',
            },
        ),
        migrations.CreateModel(
            name='ContactPhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_label', models.CharField(choices=[('DEFAULT', 'Default'), ('PERSONAL', 'Personal'), ('HOME', 'Home'), ('MOBILE', 'Mobile'), ('FAX', 'Fax'), ('DDI', 'Direct Dial In')], default='MOBILE', max_length=8, verbose_name='Phone Label')),
                ('phone_number', xero_integration.xero.utils.PossiblePhoneNumberField(max_length=128, region=None, verbose_name='Phone number')),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_phonenumbers', to='xero.contact', verbose_name='Contact/Company/Organisation')),
            ],
            options={
                'verbose_name': 'Phone number',
                'verbose_name_plural': 'Phone numbers',
                'ordering': ('phone_label', 'phone_number'),
            },
        ),
    ]
