services:
    django:
        build:
            context: .
            dockerfile: ./docker/local/django/Dockerfile
        image: xero_django
        container_name: xero_django
        ports:
            - "8000:8000"
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/app
        environment:
            - DEBUG=1
            - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1
            - CELERY_BROKER_URL=redis://redis:6379/0
        depends_on:
            - postgres_db
            - redis
    
    celery:
        build:
            context: .
            dockerfile: ./docker/local/django/Dockerfile
        image: xero_celery_worker
        container_name: xero_celery_worker
        command: celery -A config worker -l INFO
        volumes:
            - .:/app
        depends_on:
            - django

    postgres_db:
        image: postgres:latest
        container_name: xero_postgres_db
        ports:
            - "5432:5432"
        env_file:
            - .env
        volumes:
            - ./postgres_data:/var/lib/postgresql/data

    redis:
        image: redis:6
        container_name: xero_redis
volumes:
    postgres_data:

